import { describe, expect, it } from "vitest";
import {
  validateVeraConversationStatePayload,
  validateVeraHandoffPayload,
  normalizeVeraSpinStage,
  validateVeraResumoPayload,
  VERA_INGEST_AUTH_HEADER,
  VERA_INGEST_ENDPOINTS,
  VERA_RESUMO_OUTCOMES,
  VERA_SPIN_STAGES,
} from "@/lib/veraIngestContracts";

describe("Vera ingest contracts", () => {
  it("keeps the Lovable ingest endpoints named for n8n HTTP nodes", () => {
    expect(VERA_INGEST_ENDPOINTS).toEqual({
      resumo: "ingest-resumo",
      conversationState: "ingest-conversation-state",
      handoff: "ingest-handoff",
    });
    expect(VERA_INGEST_AUTH_HEADER).toBe("X-Ingest-Token");
  });

  it("accepts the resumo payload generated by the closing summary workflow", () => {
    const errors = validateVeraResumoPayload({
      user_id: "5581991495200",
      channel: "whatsapp",
      resumo: "Lead pediu avaliacao para implante e aceitou contato.",
      outcome: "agendou",
      data_agendamento: "2026-05-04T14:00:00.000Z",
      tags: ["implante", "avaliacao"],
      origem: "n8n",
    });

    expect(errors).toEqual([]);
    expect(VERA_RESUMO_OUTCOMES).toContain("transferido");
  });

  it("rejects resumo without required fields or with unknown outcome", () => {
    expect(
      validateVeraResumoPayload({
        user_id: " ",
        channel: "",
        resumo: "",
        outcome: "perdido" as never,
      }),
    ).toEqual([
      "user_id required",
      "channel required",
      "resumo required",
      "outcome must be one of agendou,recusou,transferido,abandonado",
    ]);
  });

  it("accepts SPIN stage updates sent by Vera Core", () => {
    expect(
      validateVeraConversationStatePayload({
        chat_id: "wa:5581991495200",
        channel: "whatsapp",
        spin_stage: "necessidade",
      }),
    ).toEqual([]);
    expect(VERA_SPIN_STAGES).toContain("encerramento");
  });

  it("normalizes legacy n8n SPIN stage names before Supabase insert", () => {
    expect(normalizeVeraSpinStage("situation")).toBe("situacao");
    expect(normalizeVeraSpinStage("problem")).toBe("problema");
    expect(normalizeVeraSpinStage("implication")).toBe("implicacao");
    expect(normalizeVeraSpinStage("need_payoff")).toBe("necessidade");
  });

  it("rejects unknown SPIN stage updates before they reach Supabase", () => {
    expect(
      validateVeraConversationStatePayload({
        chat_id: "wa:5581991495200",
        channel: "whatsapp",
        spin_stage: "qualificacao" as never,
      }),
    ).toEqual(["spin_stage must be one of triagem,situacao,problema,implicacao,necessidade,proposta,encerramento"]);
  });

  it("accepts handoff queue requests with minimal required data", () => {
    expect(
      validateVeraHandoffPayload({
        chat_id: "wa:5581991495200",
        channel: "whatsapp",
        motivo: "duvida_clinica",
        payload: { ultimaMensagem: "Tenho uma pergunta especifica." },
      }),
    ).toEqual([]);
  });

  it("rejects handoff requests without routing fields", () => {
    expect(validateVeraHandoffPayload({ chat_id: "", channel: "", motivo: "" })).toEqual([
      "chat_id required",
      "channel required",
      "motivo required",
    ]);
  });
});
